### ISSUE TITLE
something wrong in sample/compile_sample.sh's CHIP_ARCH

### ISSUE THREAD

**Issue by xpww** [milkv-duo/cvitek-tdl-sdk-sg200x#2]
duo 256m 的芯片是sg2002，即cv1812cp，但是compile_sample.sh的CHIP_ARCH同cvitek-tdl-sdk-cv180x目录下一样，均为CV180X。是不是这个仓库的compile_sample.sh部分代码没有修改？或者说其实cv181和cv180是兼容的？

**Comment by carbonfix** [comment]
已更新
